apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/instance: elasticsearch
  name: REDACTED
  namespace: REDACTED
spec:
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
          - dns: REDACTED-es-read-http
          - dns: REDACTED-es-write-http
          - dns: REDACTED-es-read-http.REDACTED
          - dns: REDACTED-es-write-http.REDACTED
          - dns: REDACTED-es-read-http.REDACTED.svc
          - dns: REDACTED-es-write-http.REDACTED.svc
  monitoring:
    logs:
      elasticsearchRefs:
        - name: monitoring
    metrics:
      elasticsearchRefs:
        - name: monitoring
  nodeSets:
    - config:
        node.roles:
          - master
      count: 3
      name: master
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms2g -Xmx2g'
              name: elasticsearch
              resources:
                limits: {}
                requests:
                  cpu: 250m
                  memory: 1Gi
          initContainers:
            - command:
                - /bin/bash
                - '-exc'
                - |
                  CURRENT=`sysctl -n vm.max_map_count`;
                  DESIRED="262144";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w vm.max_map_count=262144;
                  fi;
                  CURRENT=`sysctl -n fs.file-max`;
                  DESIRED="65536";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w fs.file-max=65536;
                  fi;
              image: 'docker.io/bitnami/bitnami-shell:10-debian-10-r248'
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources:
                limits: {}
                requests: {}
              securityContext:
                privileged: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
    - config:
        node.roles:
          - data
      count: 2
      name: ingest
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms10g -Xmx10g'
              name: elasticsearch
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
                requests:
                  cpu: 2
                  memory: 2Gi
          initContainers:
            - command:
                - /bin/bash
                - '-exc'
                - |
                  CURRENT=`sysctl -n vm.max_map_count`;
                  DESIRED="262144";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w vm.max_map_count=262144;
                  fi;
                  CURRENT=`sysctl -n fs.file-max`;
                  DESIRED="65536";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w fs.file-max=65536;
                  fi;
              image: 'docker.io/bitnami/bitnami-shell:10-debian-10-r248'
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources:
                limits: {}
                requests: {}
              securityContext:
                privileged: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  version: 7.16.1
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
