apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: main
spec:
  version: 7.17.18
  nodeSets:
  - name: master
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false       
      node.store.allow_mmap: false
  - name: ingest
    count: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true      
      node.store.allow_mmap: false  
  - name: storage
    count: 3
    config:
      node.roles: ["data_warm", "ingest", "data"]      
      node.store.allow_mmap: false
  - name: coordinator
    count: 3
    config:
      node.roles: [ ]
      node.store.allow_mmap: false

 # elasticsearch_password: ismail-wajdi-7415b3176
