apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/instance: elastic-monitoring
  name: combo
  namespace: elastic-mon
spec:
  nodeSets:
  - name: combo
    count: 1
    config:
      node.roles: ["master","data","ingest"]
  version: 7.17.18
