apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/instance: elastic-monitoring
  name: combo
  namespace: elastic-mon
spec:
  nodeSets:
  - name: combo
    count: 1
    config:
      node.roles: ["master","data","ingest"]
  version: 7.17.18
  initContainers:
    - command:
        - /bin/bash
        - '-exc'
        - |
       CURRENT=`sysctl -n vm.max_map_count`;
       DESIRED="262144";
       if [ "$DESIRED" -gt "$CURRENT" ]; then
           sysctl -w vm.max_map_count=262144;
       fi;
       CURRENT=`sysctl -n fs.file-max`;
       DESIRED="65536";
       if [ "$DESIRED" -gt "$CURRENT" ]; then
           sysctl -w fs.file-max=1024;
       fi;
       name: sysctl
       resources:
         limits: {}
         requests: {}
