apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/instance: elasticsearch
  name: combo
  namespace: elastic-mon
spec:
  version: 7.17.18
  monitoring:
    logs:
      elasticsearchRefs:
        - name: monitoring
    metrics:
      elasticsearchRefs:
        - name: monitoring
  nodeSets:
    - config:
        node.roles: ["data", "master", "ingest"]
      count: 1
      name: combo
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms2g -Xmx2g'
              name: elasticsearch
              resources:
                limits: {}
                requests:
                  cpu: 250m
                  memory: 4Gi
          initContainers:
          - name: increase-vm-max-map
             image: busybox
             imagePullPolicy: IfNotPresent
             command: ['sh', '-c', 'sysctl', '-w', 'vm.max_map_count=262144']
             command: ["sh", "-c", "echo", "vm.max_map_count=262144", ">>", "/etc/sysctl.conf"]
             command: ["sh", "-c", "sysctl", "-p"]
             securityContext:
               privileged: false
              image: 'docker.io/bitnami/bitnami-shell:10-debian-10-r248'
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources:
