apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/instance: elastic-monitoring
  name: combo
  namespace: elastic-mon
spec:
  nodeSets:
    - count: 1
      name: combo
      podTemplate:
        spec:
          config:
           node.roles: ["data", "master", "ingest"]
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms1g -Xmx1g'
              name: elasticsearch
              resources:
                limits: {}
                requests:
                  cpu: 250m
                  memory: 2Gi
          initContainers:
            - command:
                - /bin/bash
                - '-exc'
                - |
                  CURRENT=`sysctl -n vm.max_map_count`;
                  DESIRED="262144";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w vm.max_map_count=262144;
                  fi;
                  CURRENT=`sysctl -n fs.file-max`;
                  DESIRED="65536";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w fs.file-max=65536;
                  fi;
              image: 'docker.io/bitnami/bitnami-shell:10-debian-10-r248'
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources:
                limits: {}
                requests: {}
              securityContext:
                privileged: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 64Gi
  version: 7.16.1
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
